- name: install and configure nginx
  hosts: localhost
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: latest
      become: yes

    - name: enable and start nginx
      service:
        name: nginx
        state: started
      become:

    - name: find all html content
      find:
        paths: /usr/share/nginx/html/
        file_type: any
      register: FILES

    - name: display all files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ FILES.files }}"
      become: yes

    - name: copy Html files
