- name: install and configure nginx
  hosts: localhost
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: latest
      become: yes

    - name: enable and start nginx
      service:
        name: nginx
        state: started
      become: yes