- name: install and configure nginx
  hosts: localhost
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: latest
      become: yes

    - name: enable and start nginx
      service:
        name: nginx
        state: started
      become:

    - name: find all html content
      find:
        paths: /usr/share/nginx/html/
        file_type: any
      register: FILES

    - name: delete all html files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ FILES.files }}"
      become: yes

    - name: download and copy website content
      unarchive:
        src: https://sample-html-naveen.s3-us-west-2.amazonaws.com/buson.zip
        dest: /usr/share/nginx/html
        remote_src: yes
